# Configuración de Prometheus para SPOON
# Archivo: prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'spoon-monitor'

rule_files:
  - "alert.rules"
  - "monitoreo/alertas/*.yml"

scrape_configs:
  # SPOON CRM Principal (Next.js)
  - job_name: 'spoon-crm'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s
    honor_labels: false
    params:
      format: ['prometheus']

  # API Mobile de SPOON
  - job_name: 'spoon-api-mobile'
    static_configs:
      - targets: ['localhost:3009']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s

  # CRM Service (si está ejecutándose)
  - job_name: 'spoon-crm-service'
    static_configs:
      - targets: ['localhost:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 15s

  # PostgreSQL Exporter (opcional)
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter para métricas del sistema (opcional)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuración de almacenamiento
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    path: /prometheus
    wal-compression: true

# Configuración de logging
log:
  level: info
  format: logfmt
